### ISSUE TITLE
Some social Icons not appearing in IE11

### ISSUE THREAD

**Issue by pravarseth** [maidsafe/maidsafe.net#133]
![image](https://user-images.githubusercontent.com/37243695/43510780-994bcf1c-956e-11e8-862a-d9f7596d91da.png)

**Comment by frabrunelle** [comment]
Seems to be working fine now. Here's a screenshot I took in a VM running IE11 on Windows 7:

![VirtualBox_IE11 - Win7_27_11_2019_08_31_06](https://user-images.githubusercontent.com/1114844/69727363-69b6bb00-10f0-11ea-96ff-e7f03d9b5c64.png)
